# Generated by Django 5.2.5 on 2025-08-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
