# Generated by Django 5.2.5 on 2025-08-27 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_category_parent_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='company',
        ),
    ]
