# Generated by Django 5.2.5 on 2025-08-22 12:03

import product.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_category_image_alter_company_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=product.models.SVGAndImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
