# Generated by Django 5.2.5 on 2025-08-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='grams',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
