# Generated by Django 5.2.5 on 2025-08-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_company_number_product_grams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='number',
        ),
        migrations.AddField(
            model_name='company',
            name='phone_number',
            field=models.CharField(blank=True, max_length=123, null=True),
        ),
    ]
