# Generated by Django 5.2.5 on 2025-08-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='receiver_name',
            field=models.CharField(default=1, max_length=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='receiver_phone_number',
            field=models.CharField(default=1, max_length=123),
            preserve_default=False,
        ),
    ]
