# Generated by Django 5.2.5 on 2025-08-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_myuser_is_2fa_enabled_myuser_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
