# Generated by Django 5.2.5 on 2025-08-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_myuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
