# Generated by Django 5.2.5 on 2025-08-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_assigned_courier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('assigned', 'Назначено курьеру'), ('in_progress', 'В процессе'), ('delivered', 'Доставлено'), ('cancelled', 'Отменено')], default='Pending', max_length=50),
        ),
    ]
